version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: pytest-asyncio
    versions:
    - 0.14.0
    - 0.15.0
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pyjwt
    versions:
    - 2.0.1
