#!/bin/bash


version=$(grep -o -E "([0-9]+\.[0-9]+\.[0-9]+)" security_interface/_version.py)
echo -n "New version number (current is $version): "
read new_version
echo -n "Are you sure (yes/no)"
read answer

if echo "$answer" | grep -iq "^y" ;then
  echo "Generating new release..."
  sed -i "s/$version/$new_version/" security_interface/_version.py
  git commit -m "Bump version $new_version"
  git tag -a "$new_version" -m "$new_version"
  git push --follow-tags

else
  exit 1
fi

